### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by cyian-1756** [minetest-mods/castle_gates#1]
The readme should contain screen shots of the various gates

**Comment by kaeza** [comment]
Please no. I don't want to fetch potentially huge images when reading the README.

A wiki or some other external page with a link in README would be better IMHO.

Also, if you're doing this, please don't host screenshots in the repo itself.

**Comment by sofar** [comment]
A simple screenshot.png in 300x200 aspect is already in the mod, and that is shown in the in-game mod manager. Other screenshots can go in the forum post.

**Comment by FaceDeer** [comment]
I'll look into adding some small screenshots to the in-game documentation as well, but I think I agree with kaeza and sofar as far as the readme goes.
