### ISSUE TITLE
Missing jailbars - Jail door not craftable

### ISSUE THREAD

**Issue by H4mlet** [minetest-mods/castle_gates#5]
"castle_gates:jailbars"
They are shown as "unknown node" by the Crafting Guide mod.
Couldn't find where's the bug.

**Comment by FaceDeer** [comment]
Grr. Another recipe mistake. The recipe for castle_gates:jail_door is supposed to take jailbars as components, but I didn't notice that the jailbars are generated by the xpanes mod and don't get the castle_gates prefix.

Fix submitted. Sorry!
